// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6foDnF1tCZfYRIcdp-d1hHsvJ-ui5wSA',
    appId: '1:632665830727:web:8d0ad27b54bae3c15b0862',
    messagingSenderId: '632665830727',
    projectId: 'inclusioned-e0383',
    authDomain: 'inclusioned-e0383.firebaseapp.com',
    storageBucket: 'inclusioned-e0383.firebasestorage.app',
    measurementId: 'G-BE5BMR7078',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUk3bCcQVARThpEe2c_j-NNiMe7bghxQU',
    appId: '1:632665830727:android:6c0e858484718e075b0862',
    messagingSenderId: '632665830727',
    projectId: 'inclusioned-e0383',
    storageBucket: 'inclusioned-e0383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXa4N9cNQpqlLNV76iunDkNwpjFKSLDIk',
    appId: '1:632665830727:ios:c1980bc5fd6015d55b0862',
    messagingSenderId: '632665830727',
    projectId: 'inclusioned-e0383',
    storageBucket: 'inclusioned-e0383.firebasestorage.app',
    iosClientId: '632665830727-74a2nnu81ip8pnhrvt59dcntdp3adl6r.apps.googleusercontent.com',
    iosBundleId: 'com.inclusiveed.inclusiveEdStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXa4N9cNQpqlLNV76iunDkNwpjFKSLDIk',
    appId: '1:632665830727:ios:c1980bc5fd6015d55b0862',
    messagingSenderId: '632665830727',
    projectId: 'inclusioned-e0383',
    storageBucket: 'inclusioned-e0383.firebasestorage.app',
    iosClientId: '632665830727-74a2nnu81ip8pnhrvt59dcntdp3adl6r.apps.googleusercontent.com',
    iosBundleId: 'com.inclusiveed.inclusiveEdStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6foDnF1tCZfYRIcdp-d1hHsvJ-ui5wSA',
    appId: '1:632665830727:web:ba8af22b3cedea685b0862',
    messagingSenderId: '632665830727',
    projectId: 'inclusioned-e0383',
    authDomain: 'inclusioned-e0383.firebaseapp.com',
    storageBucket: 'inclusioned-e0383.firebasestorage.app',
    measurementId: 'G-ZXQ4RJJ19X',
  );
}
